services:

  mongo:
    image: mongo:7.0
    container_name: bigdata-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  dask-scheduler:
    build:
      context: .
      dockerfile: docker/dask.Dockerfile
    container_name: bigdata-dask-scheduler
    command: dask scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    volumes:
      - .:/app
    depends_on:
      - mongo

  dask-worker-1:
    build:
      context: .
      dockerfile: docker/dask.Dockerfile
    container_name: bigdata-dask-worker-1
    command: dask worker tcp://dask-scheduler:8786 --nthreads 1 --memory-limit 2GB
    volumes:
      - .:/app
    depends_on:
      - dask-scheduler

  dask-worker-2:
    build:
      context: .
      dockerfile: docker/dask.Dockerfile
    container_name: bigdata-dask-worker-2
    command: dask worker tcp://dask-scheduler:8786 --nthreads 1 --memory-limit 2GB
    volumes:
      - .:/app
    depends_on:
      - dask-scheduler

  dask-client:
    build:
      context: .
      dockerfile: docker/dask.Dockerfile
    container_name: bigdata-dask-client
    command: sh -lc "
      python scripts/download_dataset.py &&
      python dask/ingest.py
      "
    volumes:
      - .:/app
      - /c/Users/famil/.kaggle:/root/.kaggle:ro
    depends_on:
      - dask-scheduler
      - dask-worker-1
      - dask-worker-2
      - mongo

  spark-master:
    build:
      context: .
      dockerfile: docker/spark.Dockerfile
    container_name: bigdata-spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mongo

  spark-worker:
    build:
      context: .
      dockerfile: docker/spark.Dockerfile
    container_name: bigdata-spark-worker
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=2
    volumes:
      - .:/app
    depends_on:
      - spark-master
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile

    container_name: bigdata-api

    ports:
      - "5000:5000"

    environment:
      - MONGO_URI=mongodb://mongo:27017

    volumes:
      - .:/app

    depends_on:
      - mongo

    restart: unless-stopped

  jenkins:
    build:
      context: .
      dockerfile: docker/jenkins.Dockerfile

    container_name: bigdata-jenkins

    ports:
      - "8081:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace

    restart: unless-stopped  
volumes:
 mongo_data:
 jenkins_home:
